name: Build and Push Docker Image

on:
  push:
    branches: 
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
           username: prashola
           password: Lavanya@2407
 
      - name: Build Docker Image
        run: |
          IMAGE_NAME=prashola/k8s-demo
          docker build -t $IMAGE_NAME:${{ github.run_number }} .
 
      - name: Push Docker Image
        run: |
           IMAGE_NAME=prashola/k8s-demo
           docker push $IMAGE_NAME:${{ github.run_number }}
